name: dart_serial
description: Dart package that aims to provide a platform-independent serial port API.
version: 0.1.0-alpha.2
license: MIT
repository: https://github.com/frickly-systems/dart_serial

platforms:
  linux:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_periphery: ^0.9.5
  equatable: ^2.0.5
  glob: ^2.1.2
  meta: ^1.9.1
  path: ^1.8.3

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
